### PR TITLE
fix: properly deal with context values dropdown

### LINKED ISSUE #6217: Tech Debt: ALLOWED_CONTEXT_VALUES permutation
In order to fix the context values being filtered out of the dropdown, we hotfixed while adding a small chunk of tech debt (else if branch) to address 

```
    if (operatorValue === 'PERCENTAGE_SPLIT') {
      if (!condition.property) {
        updates.property = RuleContextValues.IDENTITY_KEY
      }

      const invalidPercentageSplit =
        condition?.value && isInvalidPercentageSplit(condition.value)
      if (invalidPercentageSplit) {
        updates.value = ''
      } else {
        updates.value = updates.value?.toString().split(':')[0]
      }
    } else if (
      // If previous operator was PERCENTAGE_SPLIT and property was IDENTITY_KEY, reset property
      condition?.operator === 'PERCENTAGE_SPLIT' &&
      condition?.property === RuleContextValues.IDENTITY_KEY
    ) {
      updates.property = ''
    }

```

### PR DESCRIPTION
**Pull request by Zaimwa9**
Thanks for submitting a PR! Please check the boxes below:
Closes #6217 

- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes
- Moved business logics within utils
- Created hook for component readibility and isolation of business logic
-

### CODE REVIEW

File: frontend/web/components/segments/Rule/Rule.tsx [hunk 1]
```diff
@@ -85,24 +85,23 @@ const Rule: React.FC<RuleProps> = ({
...
-    if (operatorValue === 'PERCENTAGE_SPLIT') {
-      if (!condition.property) {
-        updates.property = RuleContextValues.IDENTITY_KEY
-      }
+    if (shouldAutoSetIdentityKey(operatorValue, condition.property)) {
+      updates.property = RuleContextValues.IDENTITY_KEY
+    }
 
+    if (!isContextValueValidForOperator(condition.property, operatorValue)) {
+      console.log('condition.property', condition.property)
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/Rule.tsx]: is this intentional or a leftover ?

File: frontend/web/components/segments/Rule/components/RuleConditionRow.tsx [hunk 2]
```diff
@@ -12,8 +12,8 @@ import ErrorMessage from 'components/ErrorMessage'
 import RuleConditionPropertySelect from './RuleConditionPropertySelect'
 import RuleConditionValueInput from './RuleConditionValueInput'
 import { RuleContextValues } from 'common/types/rules.types'
-import { RuleContextLabels } from 'common/types/rules.types'
-import { OptionType } from 'components/base/select/SearchableSelect'
+import { useRuleOperator } from 'components/segments/Rule/hooks/useRuleOperator'
+import { useRuleContext } from 'components/segments/Rule/hooks/useRuleContext'
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/components/RuleConditionRow.tsx]: What if we shorten the imports by adding a index to /hooks ?

```tsx
import { useRuleOperator, useRuleContext} from 'components/segments/Rule/hooks'
```

File: frontend/web/components/segments/Rule/components/TextAreaModal.tsx [hunk 3]
```diff
@@ -4,15 +4,19 @@ import Button from 'components/base/forms/Button'
 import Icon from 'components/Icon'
 import Utils from 'common/utils/utils'
 import ModalHR from 'components/modals/ModalHR'
-import { checkWhitespaceIssues } from '../utils'
+import { checkWhitespaceIssues } from 'components/segments/Rule/utils/whitespaceValidation'
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/components/TextAreaModal.tsx]: We could shorten this import like:

```tsx
import { checkWhitespaceIssues } from 'components/segments/Rule/utils'
```

File: frontend/web/components/segments/Rule/hooks/useRuleContext.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
+import { RuleContextValues } from 'common/types/rules.types'
+import { getAllowedContextValuesForDropdown } from 'components/segments/Rule/utils/segmentRules'
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/hooks/useRuleContext.ts]:
```tsx
import { getAllowedContextValuesForDropdown } from 'components/segments/Rule/utils'
```

File: frontend/web/components/segments/Rule/hooks/useRuleContext.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+
+export const useRuleContext = (operator: string, property: string) => {
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/hooks/useRuleContext.ts]: We have a set of operators, right ? should we consider creating a type for it instead of using it as string ?


Something like:

```tsx
type Operator = 'EQUAL' | 'NOT_EQUAL' | 'PERCENTAGE_SPLIT' | 'GREATER' | 'LESS'

```

File: frontend/web/components/segments/Rule/hooks/useRuleOperator.ts [hunk 6]
```diff
@@ -0,0 +1,19 @@
+import Utils from 'common/utils/utils'
+import { Operator, SegmentCondition } from 'common/types/responses'
+
+export const useRuleOperator = (
+  rule: SegmentCondition,
+  operators: Operator[],
+) => {
+  const operatorObj = Utils.findOperator(rule.operator, rule.value, operators)
```
Comment (talissoncosta) [inline frontend/web/components/segments/Rule/hooks/useRuleOperator.ts]: Minor suggestion, consider renaming operatorObj to selectedOperator. In my view it make it more readable.

```tsx
  const selectedOperator = Utils.findOperator(rule.operator, rule.value, operators)
```

**Review by talissoncosta — DISMISSED** [review]
Looks pretty good @Zaimwa9 . Thanks for extract the logic.
I've added some suggestions, not blocking.

File: frontend/web/components/segments/Rule/Rule.tsx (hunk 1 above)
Comment (Zaimwa9) [reply frontend/web/components/segments/Rule/Rule.tsx]: leftover 😁

File: frontend/web/components/segments/Rule/hooks/useRuleOperator.ts (hunk 6 above)
Comment (Zaimwa9) [reply frontend/web/components/segments/Rule/hooks/useRuleOperator.ts]: Yes, I did it halfway to keep the `obj` suffix. The problem is operator at the moment is confusing as sometimes it refers to the value, sometimes the object

**Review by talissoncosta — APPROVED** [review]
Looks great!

File: frontend/web/components/segments/Rule/hooks/useRuleOperator.ts (hunk 6 above)
Comment (talissoncosta) [reply frontend/web/components/segments/Rule/hooks/useRuleOperator.ts]: I see what you mean, thanks for that.
