### PR TITLE
refactor: restore FeaturesPage RTK Query migration with MV and CR fixes

### LINKED ISSUE #5778: Migrate critical components: FeaturesPage.js
Critical component as main entrypoint of the app

State of the component:
- Class component
- 766 lines
- No typing and no hooks
- Uses HOC Providers

## Objectives
Ranked by priority
- Migrate it to a Functional component (along with TS)
- Remove the Providers injections to use RTK
- Break it in small / modular and dedicated components

### PR DESCRIPTION
**Pull request by talissoncosta**
## Summary
Restores the FeaturesPage RTK Query migration

## Changes
- Sync Flux store with RTK Query pagination/filter state
- Add E2E tests for multivariate toggle and change request workflows
- Add refetchOnFocus for features list (equivalent to #6483)
- Fix view mode toggle delay (was 5-10s, now instant) with optimistic UI updates
- Fix Groups filter not loading (was using undefined routeContext.organisationId)

### Automated (E2E)
- [x] All existing flag-tests pass

### Manual Testing

[QA List](https://github.com/Flagsmith/flagsmith/pull/6469#issuecomment-3724106792)

## Related Issues
- Restores RTK Query migration from #6428

### CODE REVIEW

**Comment by Zaimwa9** [comment]
### QA Plan

**List view (compact and normal views)**
- [ ] Enable/Disable flag from list
- [ ] Open modal
- [ ] I can search a flag
- [ ] I can filter/unfilter with a tag
- [ ] I can filter/unfilter with a value
- [ ] I can filter/unfilter with a users
- [ ] I can filter/unfilter groups
- [ ] I can sort my flags by name or created_at

**In modal**
- [ ] I can enable/disable my flag
- [ ] I can update the value of my flag -> Broken
- [ ] I can update the value of a MV option -> Broken
- [ ] I can update the weight of a MV option -> Broken
- [ ] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [ ] I can create a Feature specific segment
- [ ] I can attach a Feature specific segment
- [ ] I can attach an existing segment
- [ ] I can disable all segment
- [ ] I can save my segments
- [ ] I am redirected to user page if I want to edit an identity
- [ ] I can delete an identity
- [ ] I can add/remove a tag to me flag
- [ ] I can add custom field to my feature
- [ ] I can assign/remove users
- [ ] I can assign/remove groups
- [ ] I can add a description
- [ ] I can enable/disabled server side
- [ ] I can archive/unarchive my flag

**All of the above for (a feature on page 1 / a feature on page 3 -- broken)**
- [ ] V1 versioned environment
- [ ] V1 versioned + Feature Change requests
- [ ] V1 Version + Feature CR + Segment CR
- [ ] V1 Version + Segment CR
- [x] V2 versioned environment enabled
- [x] V2 env + FCR
- [ ] V2 env + FCR + SCR
- [ ] V2 env + SCR

_for CR => new states are reflected when committed_

File: frontend/common/utils/featureFilterParams.ts [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+  return arr.join(',')
+}
+
+/** Parses comma-separated string into number array */
+function parseIntArray(value: string | string[] | undefined): number[] {
+  if (!value || typeof value !== 'string') return []
+  return value
+    .split(',')
+    .filter((v) => v)
+    .map((v) => parseInt(v, 10))
```
Comment (Zaimwa9) [inline frontend/common/utils/featureFilterParams.ts:27]: We could filter out NaN here

**Comment by talissoncosta** [comment]
### QA Plan - V2 and V2 + SCR

**List view (compact and normal views)**
- [x] Enable/Disable flag from list
- [x] Open modal
- [x] I can search a flag
- [x] I can filter/unfilter with a tag
- [ ] I can filter/unfilter with a value ( clear value is not working properly )
- [x] I can filter/unfilter with a users
- [x] I can filter/unfilter groups
- [x] I can sort my flags by name or created_at

**In modal**
- [x] I can enable/disable my flag
- [x] I can update the value of my flag 
- [x] I can update the value of a MV option
- [x] I can update the weight of a MV option
- [x] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [x] I can create a Feature specific segment
- [x] I can attach a Feature specific segment
- [x] I can attach an existing segment
- [x] I can disable all segment
- [x] I can save my segments
- [x] I am redirected to user page if I want to edit an identity
- [x] I can delete an identity
- [x] I can add/remove a tag to me flag
- [x] I can add custom field to my feature
- [x] I can assign/remove users
- [x] I can assign/remove groups
- [x] I can add a description
- [x] I can enable/disabled server side
- [x] I can archive/unarchive my flag


Issues found:
- [x] Clear all is not working properly for "value" filter - Pre-existing issue, it is gonna be handle separately on this [issue](https://github.com/Flagsmith/flagsmith/issues/6523)
- [ ] Failed to add an identity override for a MV feature - Present on main ( I think it might be related to the fix on this [PR](https://github.com/Flagsmith/flagsmith/pull/6515))
    - Steps to reproduce
       - Create a feature with MV
       - Navigate to Identities
       - Click in one of the existing identifiers
       - Find the feature I've just created
       - Open the modal and click "Update feature"

**Comment by Zaimwa9** [comment]
### QA Plan
**Env V1**

**List view (compact and normal views)**
- [x] Enable/Disable flag from list
- [x] Open modal
- [x] I can search a flag
- [x] I can filter/unfilter with a tag
- [ ] I can filter/unfilter with a value 🔴  Failing => Cannot clear if we are filtering on a value (not talking about enabled / disabled)
- [x] I can filter/unfilter with a users
- [x] I can filter/unfilter groups
- [x] I can sort my flags by name or created_at

**In modal**
- [x] I can enable/disable my flag
- [ ] I can update the value of my flag  => 🔴 
- [x] I can update the value of a MV option 
- [x] I can update the weight of a MV option
- [x] I can create a MV option
- [x] I can delete a MV option
- [x] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [x] I can create a Feature specific segment
- [ ] I can attach a Feature specific segment => 🔴  => After updating the feature with segment it loses the state and goes to "create feature modal"
- [ ] I can attach an existing segment => 🔴 => same
- [ ] I can disable all segment => 🔴 => same
- [ ] I can save my segments => 🔴  => same
- [x] I am redirected to user page if I want to edit an identity
- [x] I can delete an identity
- [ ] I can add/remove a tag to my flag => 🔴 => Same behavior as segments => Interesting enough it doesn't happen when there is a custom field
- [ x] I can update a custom field on my feature 
- [ ] I can assign/remove users => 🔴  => same
- [ ] I can assign/remove groups => 🔴 => Same going back to create feature
- [ ] I can add a description => 🔴  => same
- [ ] I can enable/disabled server side => 🔴 => same
- [ ] I can archive/unarchive my flag => 🔴  same

image

File: frontend/web/components/tables/TableValueFilter.tsx [hunk 2]
```diff
@@ -34,17 +34,25 @@ const TableTagFilter: FC<TableFilterType> = ({
...
       onChange({
         enabled: value.enabled,
-        valueSearch: search,
+        valueSearch: search || null,
       })
     }
-  }, [search, value])
+
+    prevValueSearchRef.current = value?.valueSearch
+  }, [value?.valueSearch, search, value.enabled, onChange, resetSearch])
```
Comment (Zaimwa9) [inline frontend/web/components/tables/TableValueFilter.tsx]: @talissoncosta 
I see the intent but this was the root of the settings update bug. OnChange and resetSearch are not memoized which first caused the useEffect to be triggered on every interaction (catchable by adding a log into it).

This is not the cleanest maybe but separating the resetting / searching in 2 different useEffects allows to fix the bug and fix the `clearAll`.

I think a long-term solution to explore here would be to have the `debouncedSearch` wrapped in the filters hook and this one only displays and use callbacks (to be confirmed)

I would just fix it here and leave improvements for later

**Review by Zaimwa9 — CHANGES_REQUESTED** [review]

File: frontend/web/components/tables/TableValueFilter.tsx (hunk 2 above)
Comment (talissoncosta) [reply frontend/web/components/tables/TableValueFilter.tsx]: Agree, thanks my friend!

**Comment by Zaimwa9** [comment]
### QA Plan ENV V1 bis

**List view (compact and normal views)**
- [x] Enable/Disable flag from list
- [x] Open modal
- [x] I can search a flag
- [x] I can filter/unfilter with a tag
- [ ] I can filter/unfilter with a value 🟠  => discussed following PR
- [x] I can filter/unfilter with a users
- [x] I can filter/unfilter groups
- [x] I can sort my flags by name or created_at

**In modal**
- [x] I can enable/disable my flag
- [x] I can update the value of my flag 
- [x] I can update the value of a MV option 
- [x] I can update the weight of a MV option
- [x] I can create a MV option
- [x] I can delete a MV option
- [x] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [x] I can create a Feature specific segment
- [x] I can attach a Feature specific segment 
- [x] I can attach an existing segment
- [x] I can disable all segment
- [x] I can save my segments
- [x] I am redirected to user page if I want to edit an identity
- [x] I can delete an identity
- [x] I can add/remove a tag to my flag
- [x] I can update a custom field on my feature 
- [x] I can assign/remove users
- [x] I can assign/remove groups
- [x] I can add a description
- [x] I can enable/disabled server side
- [x] I can archive/unarchive my flag

**Comment by Zaimwa9** [comment]
### QA Plan ENV V1 With change requests

**List view (compact and normal views)**
- [x] Open modal
- [x] I can search a flag
- [x] I can filter/unfilter with a tag
- [ ] I can filter/unfilter with a value 🟠  => discussed following PR
- [x] I can filter/unfilter with a users
- [x] I can filter/unfilter groups
- [x] I can sort my flags by name or created_at

**In modal**
- [x] I can enable/disable my flag
- [x] I can update the value of my flag 
- [x] I can update the value of a MV option 
- [x] I can update the weight of a MV option
- [x] I can create a MV option
- [x] I can delete a MV option
- [x] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [x] I can create a Feature specific segment
- [x] I can attach a Feature specific segment 
- [x] I can attach an existing segment
- [x] I can disable all segment
- [x] I can save my segments
- [x] I am redirected to user page if I want to edit an identity
- [x] I can delete an identity
- [x] I can add/remove a tag to my flag
- [x] I can update a custom field on my feature 
- [x] I can assign/remove users
- [x] I can assign/remove groups
- [x] I can add a description
- [x] I can enable/disabled server side
- [x] I can archive/unarchive my flag

**Comment by talissoncosta** [comment]
## Known Issue - Value Filter Clear

There's a known issue where the "Clear all" filters button doesn't properly clear the Value filter due to race conditions with debounced state.

**Issue:** #6523

This will be addressed in a follow-up PR as it requires changes to the shared `useDebouncedSearch` hook and proper callback memoization across multiple components.

**Comment by talissoncosta** [comment]
### QA Plan ENV V2 With change requests

**List view (compact and normal views)**
- [x] Open modal
- [x] I can search a flag
- [x] I can filter/unfilter with a tag
- [x] I can filter/unfilter with a value 🟠  => [Issue](https://github.com/Flagsmith/flagsmith/issues/6523) created to handle that
- [x] I can filter/unfilter with a users
- [x] I can filter/unfilter groups
- [x] I can sort my flags by name or created_at

**In modal**
- [x] I can enable/disable my flag
- [x] I can update the value of my flag 
- [x] I can update the value of a MV option
- [x] I can update the weight of a MV option
- [x] I can create a MV option
- [x] I can delete a MV option
- [x] I can add a feature to a release pipeline
- [ ] I can remove a feature from a release pipeline (if applicable)
- [x] I can create a Feature specific segment
- [x] I can attach a Feature specific segment
- [x] I can attach an existing segment
- [x] I can disable all segment
- [x] I can save my segments
- [x] I am redirected to user page if I want to edit an identity
- [x] I can delete an identity
- [x] I can add/remove a tag to my flag
- [x] I can update a custom field on my feature 
- [x] I can assign/remove users
- [x] I can assign/remove groups
- [x] I can add a description
- [x] I can enable/disabled server side
- [x] I can archive/unarchive my flag

**Review by Zaimwa9 — APPROVED** [review]
