### PR TITLE
fix: User display name

### LINKED ISSUE #5710: If user first and last name is missing from user profile, the assignee in change request is blank
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When you assign a user to a change request, and that user is missing their name information, the assignee on the change request is blank, which is confusing UX. It's somewhat of an edge case, however it's entirely possible to create an account missing this information via SAML. 

### Steps To Reproduce

Create an account via SAML that is missing first name and last name. 

Create that change request and assign it to that user. 

### Expected behavior

Rather than appear blank, it should perhaps default to displaying the user email instead. 

### Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Some users may not have a first name / last name set, there were various touch points where we were relying on it. Instead, this creates a generic approach where we fallback to email.

## How did you test this code?

Viewed touchpoints as a user without a name 
image

### CODE REVIEW

File: frontend/common/utils/utils.tsx [hunk 1]
```diff
@@ -278,58 +279,6 @@ const Utils = Object.assign({}, require('./base/_utils'), {
       timeUnit: TimeUnit.MINUTE,
     }
   },
-  getExistingWaitForTime: (
```
Comment (kyle-ssg) [inline frontend/common/utils/utils.tsx:281]: Note: not sure what happened here but there were 3 instances of this function

**Review by Zaimwa9 — APPROVED** [review]
