### PR TITLE
fix: organisation billing styling issues

### LINKED ISSUE #6246: Organisation billing styling issues
There are a few styling issues in the billing section of organisation settings as can be seen in the following screenshot. 

 1. The header section of the enterprise panel is unreadable
 2. The bullet markers are visible on each of the points in the main content of the panel
 3. The alignment of the buttons on each of the panels is off - they should match in their vertical alignment

Image

### PR DESCRIPTION
**Pull request by talissoncosta**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

This PR fixes styling issues in the organisation billing section (closes #6246).
### Styling Fixes (Fixes #6246)

image

- **Fixed Enterprise panel header readability:**

  - Improved text color contrast for header content in enterprise panels

- **Fixed bullet markers visibility:**

  - Removed list-style from pricing features list items
  - Added CSS rule to hide bullet markers (`.pricing-features > li { list-style: none; }`)

- **Fixed button alignment:**
  - Improved vertical alignment of buttons across pricing panels
  - Ensured consistent spacing and positioning

## Benefits
- ✅ **Fixed styling issues**: Resolves issues reported in #6246

## Testing
- ✅ Styling fixes verified:
  - Enterprise panel header is now readable
  - Bullet markers are hidden in feature lists
  - Buttons are properly aligned across panels

## Related Issues

Closes #6246

### CODE REVIEW

**Comment by talissoncosta** [comment]
Hey @matthewelwell , I checked the commit history and this seems to be the intended look. Can you confirm please ?

**Comment by matthewelwell** [comment]
> Hey @matthewelwell , I checked the commit history and this seems to be the intended look. Can you confirm please ?

Looks great, thanks!

File: frontend/web/components/modals/payment/constants.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export const ENTERPRISE_ICON_COLOR = '#F7D56E'
+export const PRIMARY_ICON_COLOR = '#27AB95'
+
+// URLs
+export const CONTACT_US_URL = 'https://www.flagsmith.com/contact-us'
```
Comment (talissoncosta) [inline frontend/web/components/modals/payment/constants.ts]: My idea was to extract the values that were being used in multiple places and export as a const

**Comment by talissoncosta** [comment]
@claude review this PR

File: frontend/global.d.ts [hunk 2]
```diff
@@ -24,6 +26,26 @@ declare namespace UniversalAnalytics {
...
+}
+
+type ProjectConfig = {
+  api: string
+  chargebee?: {
+    site: string
+  }
+  plans?: ProjectPlans
+}
+
```
Comment (Zaimwa9) [inline frontend/global.d.ts]: As you did with Payment/types, maybe we could move them in a proper type file and leave in this file only what must be in global

File: frontend/web/components/modals/payment/Payment.tsx [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+  viewOnly?: boolean
+  isDisableAccountText?: string
+}
+
+export const Payment = ({ isDisableAccountText, viewOnly }: PaymentProps) => {
+  const [yearly, setYearly] = useState(true)
+
+  const organisation = AccountStore.getOrganisation()
+  const plan = organisation?.subscription?.plan ?? ''
+  const isAWS = organisation?.subscription?.payment_method === 'AWS_MARKETPLACE'
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/Payment.tsx]: Maybe we should use an enum here or at least `payment_method: AWS_MARKETPLACE | etc`

Knowing that those are the ones i see in the backend:
```
CHARGEBEE = "CHARGEBEE"
XERO = "XERO"
AWS_MARKETPLACE = "AWS_MARKETPLACE"
```

File: frontend/web/components/modals/payment/Payment.tsx [hunk 4]
```diff
@@ -0,0 +1,129 @@
+import React, { FC, useState, useEffect } from 'react'
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/Payment.tsx]: FC unused :) 
```suggestion
import React, { useState, useEffect } from 'react'
```

File: frontend/web/components/modals/payment/PaymentButton.tsx [hunk 5]
```diff
@@ -0,0 +1,56 @@
+// @ts-ignore
+import _data from 'common/data/base/_data'
+
+export type PaymentButtonProps = {
+  'data-cb-plan-id'?: string
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/PaymentButton.tsx]: Can we change this to some planId or something ?

File: frontend/web/components/modals/payment/PricingPanel.tsx [hunk 6]
```diff
@@ -0,0 +1,162 @@
...
+        >
+          <div
+            style={{
+              display: 'flex',
+              flexDirection: 'column',
+              height: '100%',
+              minHeight: '200px',
+            }}
+          >
+            <div style={{ flex: '0 0 auto' }}>
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/PricingPanel.tsx]: Can you check if we can use existing classes to do this ?

File: frontend/web/components/modals/payment/Payment.tsx [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+
+type PaymentProps = {
+  viewOnly?: boolean
+  isDisableAccountText?: string
+}
+
+export const Payment = ({ isDisableAccountText, viewOnly }: PaymentProps) => {
+  const [yearly, setYearly] = useState(true)
+
+  const organisation = AccountStore.getOrganisation()
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/Payment.tsx]: Ideally we should move away from the stores. I know it might a bit out of scope but if we could have a hook (or any alternative you see) to access the organisation in TS way, that would be a really great improvement (and use it at least in those new files).

Check maybe `account-store.js` and `useOrganisation` (RTK) to see how it's done:
```
  selectOrganisation: (id) => {
    API.setCookie('organisation', `${id}`)
    store.organisation = _.find(store.model.organisations, { id })
    store.changed()
  },
```

File: frontend/web/components/modals/payment/Payment.tsx [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+                <BlockedOrgInfo />
+              </div>
+            </div>
+          )}
+        </Row>
+
+        <PricingToggle isYearly={yearly} onChange={setYearly} />
+
+        <Row className='pricing-container align-start'>
+          <PricingPanel
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/Payment.tsx]: NIT: a bit overkill, honestly i'm fine if you prefer to leave it like this as we have only 2 plans here.

What do you think about putting the config in a plansConfig = [{title: 'Start-up'}] etc above and map over them here ? Cleaner to read the config imo but again, not so important

File: frontend/web/components/modals/payment/pricingFeatures.tsx [hunk 9]
```diff
@@ -0,0 +1,75 @@
+import { PricingFeature } from './types'
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/pricingFeatures.tsx]: NIT: Can we maybe rename this file to add config or constants for later brain satisfaction?

File: frontend/web/components/modals/payment/types.ts [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+  }
+}
+
+type ChargebeeSDK = {
+  init: (config: { site: string }) => void
+  registerAgain: () => void
+  getInstance: () => ChargebeeInstance
+}
+
+declare global {
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/types.ts]: Mmh.. Why not have it in the `global.d.ts`, I don't have an answer but i'm just thinking that ideally we should have as less possible in the global declaration, so it might be better to have them all in one place to not forget about some hidden ones

File: frontend/web/components/modals/payment/constants.ts [hunk 11]
```diff
@@ -0,0 +1,11 @@
+export const ENTERPRISE_ICON_COLOR = '#F7D56E'
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/constants.ts]: Ah yes, we already have constants (see comment on the pricingFeatures), maybe it would be noisy to have them there but an indication that the other file is declaration focused would help

File: frontend/web/components/modals/payment/PricingPanel.tsx [hunk 12]
```diff
@@ -0,0 +1,162 @@
...
+  priceYearly?: string
+  isYearly: boolean
+  viewOnly?: boolean
+  chargebeePlanId?: string
+  isPurchased?: boolean
+  isEnterprise?: boolean
+  isDisableAccount?: string
+  features: PricingFeature[]
+  headerContent?: ReactNode
+  onContactSales?: () => void
```
Comment (Zaimwa9) [inline frontend/web/components/modals/payment/PricingPanel.tsx]: NIT: If ever you come up with a way to lighten a bit this props (if it's very low effort), could be nice. Otherwise let's leave it for next pass

**Review by Zaimwa9 — CHANGES_REQUESTED** [review]
Thanks, overall very good improvements. Couple of minor comments. One to me seems a bit more important than the others: getting rid of account-store. It would be amazing to start have it the structure to move the chunky component there

File: frontend/global.d.ts (hunk 2 above)
Comment (talissoncosta) [reply frontend/global.d.ts]: It seems that this Project is a global type definition, I was trying to dig a little deeper on it to understand. However, it has been used outside Payment as well. So I am still not sure how to place them tbh...

Comment (talissoncosta) [reply frontend/global.d.ts]: Project is also used on ProjectsPage.tsx.

File: frontend/web/components/modals/payment/Payment.tsx (hunk 4 above)
Comment (talissoncosta) [reply frontend/web/components/modals/payment/Payment.tsx]: Good catch!

File: frontend/web/components/modals/payment/PaymentButton.tsx (hunk 5 above)
Comment (talissoncosta) [reply frontend/web/components/modals/payment/PaymentButton.tsx]: Totally, I missed that!

File: frontend/web/components/modals/payment/types.ts (hunk 10 above)
Comment (talissoncosta) [reply frontend/web/components/modals/payment/types.ts]: Yep, you are right, as it is a global type definition it should live there, same as Project

File: frontend/web/components/modals/payment/Payment.tsx (hunk 8 above)
Comment (talissoncosta) [reply frontend/web/components/modals/payment/Payment.tsx]: I agree, let's make PlansConfig our single source of truth.

File: frontend/web/components/modals/Payment.js [hunk 13]
```diff
@@ -264,8 +270,14 @@ const Payment = class extends Component {
                   </Flex>
                   <Flex className='pricing-panel bg-primary900 text-white p-2'>
                     <div className='panel panel-default'>
-                      <div className='panel-content p-3 pt-4'>
-                        <span className='featured text-body'>
+                      <div
+                        className='panel-content p-3 pt-4 d-flex flex-column justify-content-between'
+                        style={{
+                          backgroundColor: 'rgba(39, 171, 149, 0.08)',
```
[the remark this answers is not in the document]
Comment (talissoncosta) [reply frontend/web/components/modals/Payment.js:276]: image

**Comment by talissoncosta** [comment]
Hey @Zaimwa9
I am sorry for that, talking to @matthewelwell we have decided to split this work and handle only the styling issues on this PR. Your code review was super helpful and it will be  helpful on the next issue [#6283](https://github.com/Flagsmith/flagsmith/pull/6283), that I will handle the full migration properly. :pray:
 [](edited-with-Axolo)

**Review by Zaimwa9 — APPROVED** [review]

**Comment by talissoncosta** [comment]
Hey @matthewelwell
It seems I got merge blocked by an unresolved conversation that got lost after I reduce the scope on this PR ( force push ). Can you help me unblock it ? :smile:
image
 [](edited-with-Axolo)

**Comment by matthewelwell** [comment]
@talissoncosta done
