### PR TITLE
fix: #6397 - Inconsistent feature toggle behavior corrected

### LINKED ISSUE #6397: UX bug: Inconsistent feature toggle behaviour based on window size
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When toggling a flag from the browser with a full-sized window, you get the experience in the screenshot below:

Image

When the browser window is narrow, clicking the toggle instead opens a feature-specific view to make changes:

Image

### Steps To Reproduce

1. Open your browser (in my case chromium-based) at half-width
2. Click the toggle to enable/disable a feature in the dashboard
3. Notice how it opens the feature in a new view

### Expected behavior

The enable/disable confirmation toggle appears in step 3 as it does for a fullwidth browser.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Mythindia**
Inconsistent feature toggle behavior fixed by preventing event bubbling

Thanks for submitting a PR! Please check the boxes below:

- [x] I have read the [Contributing Guide](/CONTRIBUTING.md).
- [ ] I have added information to `docs/` if required so people know about the feature.
- [x] I have filled in the "Changes" section below.
- [x] I have filled in the "How did you test this code" section below.

## Changes

Closes https://github.com/Flagsmith/flagsmith/issues/6397

Inconsistent feature toggle behavior based on window size

Description:

Full-width screens: Clicking the feature toggle switch displays a confirmation modal (correct behavior)
Narrow screens: Clicking the feature toggle switch opens the feature detail view instead of showing the confirmation modal (incorrect behavior)
**Root Cause:**
The feature flag list component (FeatureRow.tsx) had two responsive rendering branches:

Large screens (d-lg-flex): The toggle Switch was properly wrapped with onClick={(e) => { e.stopPropagation() }} to prevent event bubbling
Narrow screens (d-lg-none): The toggle Switch was missing this event propagation blocker
When users clicked the toggle on narrow screens, the click event bubbled up to the parent row's onClick={() => editFeature()} handler, which opened the feature detail view instead of allowing the toggle confirmation modal to appear.

**Solution**
Event Propagation Handler (FeatureRow.tsx)
Added onClick={(e) => { e.stopPropagation() }} wrapper around the narrow-screen Switch component to prevent click events from bubbling to the parent row's click handler.

## How did you test this code?

Open your browser (in my case chromium-based) at half-width
Click the toggle to enable/disable a feature in the dashboard
Notice how it opens the feature in a new view

### CODE REVIEW

File: frontend/web/components/feature-summary/FeatureRow.tsx [hunk 1]
```diff
@@ -380,6 +385,7 @@ const FeatureRow: FC<FeatureRowProps> = (props) => {
             checked={displayEnabled}
             onChange={onChange}
           />
+          </div>
```
Comment (talissoncosta) [inline frontend/web/components/feature-summary/FeatureRow.tsx]: Could you please check the indentation in here ?

**Review by talissoncosta — CHANGES_REQUESTED** [review]
Thanks for your contribution. I've just added a minor comment.

File: frontend/web/components/feature-summary/FeatureRow.tsx (hunk 1 above)
Comment (Mythindia) [reply frontend/web/components/feature-summary/FeatureRow.tsx]: Thank you for the review, A new commit with proper indentation has been made.

**Review by talissoncosta — APPROVED** [review]
Looks good, thanks so much for your contribution!
